listen = "0.0.0.0"
port   = 9997
service_ip = "" #注册服务发现使用ip，后续访问也将通过此ip访问，必须绑定设置

##enable tcp service
enable = true

[groups]

    [groups.1]
     name   = "group1"
     ##group filter like filter=["test.*"]
     filter = []

    [groups.2]
     name   = "group2"
     filter = []
