##cluster config
enable = true
##支持以consul、mysql、redis、ssdb方式进行集群控制
##根据type配置的不同，以下配置可选其一
type = "mysql"

[consul]
service_ip = "127.0.0.1:8500"

[mysql]
##参照doc/cluster.db.md文档进行数据表的创建
##只需要将wing-binlog-go配置到相同的库和表上即可构建一个集群
addr      = "127.0.0.1"
port      = 3306
user      = "root"
password  = "123456"
database  = "wing-binlog-cluster"
charset   = "utf8"

[redis]
addr = "127.0.0.1"
port = 6379

[ssdb]
addr = "127.0.0.1"
port = 8888
