[client]
slave_id      = 9999
ignore_tables = ["Test.abc", "Test.123"] ##这里必须是个数组，为空请写成[]
bin_file      = ""
bin_pos       = 0

[mysql]
host     = "127.0.0.1"
user     = "root"
password = "123456"
port     = 3306
charset  = "utf8"
dbname   = "wordpress"
    