##mode 支持广播和权重的方式，广播意味着，事件发生的时候会通知到所有的url
##权重意味着依据权重自动负载均衡，如果为0或者想等，则自动平均负载
##权重值范围为0-100
##设定mode模式为广播时weight值无效
##tcp连接到wing-binlog-go时可以选择加入到组和设定权重，依据为组的名称
##当组的名称对应的mode为广播时，权重无效
##当组的mode为权重时，将依据设定的权重自动负载均衡
[groups]
    [group1]
     mode = "broadcast" ##(广播)broadcast or  (权重)weight
     name = "group1"

    [group2]
     mode = "weight"
     name = "group2"
