listen = "0.0.0.0"
port   = 9998

##enable tcp service
enable = true

[groups]

    [groups.1]
     name   = "group1"
     ##group filter like filter=["test.*"]
     filter = []

    [groups.2]
     name   = "group2"
     filter = []
